### PR TITLE
Feature arch. in artefact names

### LINKED ISSUE #351: Consider `arch` in released file names
#### Is your feature request related to a problem?

No.

#### Describe the feature you'd like

I'd like to discuss if we should consider having `arch` as part of the generated file names: this is all for macOS, so maybe it's not an issue at this moment (?). Does more recent macOS even support AMD (I think I saw a community project once, so not official (?))?

#### Describe alternatives you've considered

Keeping it as-is, for now.

#### Additional context

I think the builders we use for e.g. `setup-beam` (from Hex/Bob) will soon start to be fetched from an endpoint that contains the `arch` but since they're Linux that might make more sense (and only there (?)).

### PR DESCRIPTION
**Pull request by paulo-ferraz-oliveira**
# Description

Closes #351.

- [x] I have performed a self-review of my changes
- [x] I have read and understood the [contributing guidelines](https://github.com/jelly-beam/otp-macos/blob/main/CONTRIBUTING.md)

### CODE REVIEW

**Comment by paulo-ferraz-oliveira** [comment]
Will wait for #359 because the build process is broken.

**Comment by paulo-ferraz-oliveira** [comment]
I'm leaving this running for the night, but since 12 is ✅, I'm hopeful 13, and 14 will be too.

**Comment by starbelly** [comment]
14 failed, what would you like to do here?

**Comment by starbelly** [comment]
Hi @paulo-ferraz-oliveira , I see this has conflicts.

**Comment by paulo-ferraz-oliveira** [comment]
Thanks. I'll fix this when I'm closer to the computer.

**Comment by paulo-ferraz-oliveira** [comment]
Branch has been rebased and force-pushed.

**Comment by paulo-ferraz-oliveira** [comment]
This is building at least one artefact, which means that subsequent failures would be handled by our process. I'm merging so we can start generating stuff for general consumption.

**Pull request merged**
